component: web
replicas: 1

image:
  repository: ghcr.io/GiladTrachtenberg/video-demo-web
  tag: ""

migrations:
  enabled: false

health:
  liveness: /
  readiness: /
  port: 80

service:
  enabled: true
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080

env:
  API_UPSTREAM: video-demo-api:8000
