component: web
replicas: 1
image:
  repository: ghcr.io/giladtrachtenberg/video-demo-web
  tag: "88b77d574d4ef98fb9e9959022fb9fd31c36d69f"
migrations:
  enabled: false
health:
  liveness: /
  readiness: /
  port: 80
service:
  enabled: true
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080
env:
  API_UPSTREAM: video-demo-api:8000
