component: web
replicas: 1
image:
  repository: ghcr.io/giladtrachtenberg/video-demo-web
  tag: "bd2965f01e1dfa3690aa0b28a0410b06a1b77749"
migrations:
  enabled: false
health:
  liveness: /
  readiness: /
  port: 80
service:
  enabled: true
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080
env:
  API_UPSTREAM: video-demo-api:8000
