component: worker
replicas: 2
image:
  repository: ghcr.io/giladtrachtenberg/video-demo
  tag: "b245c6f1b636bf50ea372b7653aa3f2c47f7b1d1"
migrations:
  enabled: false
commandOverride:
  command: ["celery"]
  args: ["-A", "src.tasks", "worker", "--loglevel=info", "--concurrency=2"]
service:
  enabled: false
configMap:
  enabled: true
  data:
    APP_NAME: video-demo
    DEBUG: "false"
    MINIO_BUCKET: video-demo
    MINIO_SECURE: "false"
sharedSecrets:
  - app-shared-secrets
